sudo: false
language: c
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
matrix:
  include:
  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    compiler: ': #GHC 7.10.3'
    addons:
      apt:
        packages:
        - cabal-install-1.22
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver lts-5"
    compiler: ': #stack 7.10.3'
    addons:
      apt:
        packages:
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ': #stack nightly'
    addons:
      apt:
        packages:
        - libgmp-dev
  - env: BUILD=stack ARGS="--resolver lts-5"
    compiler: ': #stack 7.10.3 osx'
    os: osx
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ': #stack nightly osx'
    os: osx
  allow_failures:
  - env: BUILD=cabal GHCVER=head  CABALVER=head
  - env: BUILD=stack ARGS="--resolver nightly"
before_install:
- unset CC
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  case "$BUILD" in
    stack)
      stack --no-terminal --install-ghc $ARGS test --only-dependencies
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS
      ;;
  esac
script:
- |
  case "$BUILD" in
    stack)
      stack --no-terminal $ARGS test --haddock --no-haddock-deps
      ;;
    cabal)
      cabal configure --enable-tests --enable-benchmarks -v2 --ghc-options="-O0 -Werror"
      cabal build
      cabal check || [ "$CABALVER" == "1.16" ]
      cabal test
      cabal sdist
      cabal copy
      SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && \
        (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
      ;;
  esac
deploy:
  provider: releases
  api_key:
    secure: 21E7t77mBF8IKFDZ+7a7rc9uxQ5vYKKudsXFjQLamZu67f4F/NWBNxOkqT7j0fTC6FVitMRD7k1OG6LVHndGPiar39ejoJovgVqJhGN6bcPHGg/J32ou72ayFz73D2QfAHnhZKpZlr6m7NYtRsf9Eb+fHzywpZQhcHVIGeqdDqOgtqk3bNSVSnsDu59a6/7k58+Ru1uvIJ9F3RhKCDf8iizv31NKcgBzbTFlBZphmSapbRr2ROTZn2MSZufG7LA4r6QYOHho799LcyMWj94yapYy8j+Vp3EcDA8XPxapl8EPLQmFJqP3obunWkJ9dqVIRFzCPrSGmOMfjPQbb17Ag9YN2zubLtxc1SxZyH7e3j9tHxuSGws6qYIbfH4jxRPKexCUEIQ1wOZZj2vvyO0LIJFn9HNJhJyoNWX58gWzYLtq88W6ETnnDDsHGrAHGarkdb9bFmZq/+R5cZVC7f7GGTJb7KHXB7+GVmwx1oyjDgDnyXEKJYmxgKHimdOD+KdXm+IcWUbl7Q1W0BRCJNhpE++ONFic0xHusKbgLceISsPjqypGkm9sNMTdVNe+BZAgaSM4ixTG6SK+zdq/Tj+6ejG9odmyP57ii9JJmwx3V0/ZesQl3lea6lniMsBPuOQABtgauue4NpC2DsmussGNfpPtOThn4syBndhILHmdmjw=
  file: .stack-work/dist/*/Cabal-1.22.5.0/build/hmonit-exe/hmonit-exe
  on:
    repo: pwestling/hmonit
